### PR TITLE
Added remaining events

### PR DESCRIPTION
**Pull request by fennekit**
Added events 'select', 'doubleClick', 'click', 'contextmenu'

### CODE REVIEW

**Comment by cdjackson** [comment]
Thanks.
Why have you removed the $scope.component member?

**Comment by fennekit** [comment]
Hi Chris,

The version from gh-pages did not give any errors while using it. The
master page did. The difference was the $scope.component member

Erik

On Thu, May 7, 2015 at 10:12 PM, Chris Jackson <notifications@github.com>
wrote:

> Thanks.
> Why have you removed the $scope.component member?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/visjs/angular-visjs/pull/26#issuecomment-100003327>.
>



-- 
Met vriendelijke groet/Kind Regards,

Erik Konijnenburg
http://www.fennek-it.nl
+31 6 24218265

[image: View Erik Konijnenburg's profile on LinkedIn]
<http://nl.linkedin.com/pub/erik-konijnenburg/47/106/284>

Op onze aanbiedingen zijn de Algemene Voorwaarden
<http://www.fennek-it.nl/Algemene%20Voorwaarden.pdf> van toepassing.

**Comment by cdjackson** [comment]
Hmm - ok, I’ll take a look. This was recently added by someone else and I didn’t test it (I know - that’s bad!). The idea is that you can use it to access the vis object…

I’ll take a look in the next day or so…

(and thanks for the PR by the way).

Cheers
Chris

**Comment by fennekit** [comment]
The error was:

Error: [$compile:nonassign] Expression 'undefined' used with directive
'visTimeline' is non-assignable!
http://errors.angularjs.org/1.3.15/$compile/nonassign?p0=undefined&p1=visTimeline
    at angular.js:63
    at parentSet (angular.js:7700)
    at parentValueWatch (angular.js:7713)
    at Object.regularInterceptedExpression (angular.js:12911)
    at Scope.$digest (angular.js:14300)
    at Scope.$apply (angular.js:14571)
    at done (angular.js:9698)
    at completeRequest (angular.js:9888)
    at XMLHttpRequest.requestLoaded (angular.js:9829)

On Thu, May 7, 2015 at 10:26 PM, Chris Jackson <notifications@github.com>
wrote:

> Hmm - ok, I’ll take a look. This was recently added by someone else and I
> didn’t test it (I know - that’s bad!). The idea is that you can use it to
> access the vis object…
>
> I’ll take a look in the next day or so…
>
> (and thanks for the PR by the way).
>
> Cheers
> Chris
>
>
>
> > On 7 May 2015, at 21:21, Fennek IT <notifications@github.com> wrote:
> >
> > Hi Chris,
> >
> > The version from gh-pages did not give any errors while using it. The
> > master page did. The difference was the $scope.component member
> >
> > Erik
> >
> > On Thu, May 7, 2015 at 10:12 PM, Chris Jackson <notifications@github.com
> >
> > wrote:
> >
> > > Thanks.
> > > Why have you removed the $scope.component member?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/visjs/angular-visjs/pull/26#issuecomment-100003327
> >.
> > >
> >
> >
> >
> > --
> > Met vriendelijke groet/Kind Regards,
> >
> > Erik Konijnenburg
> > http://www.fennek-it.nl
> > +31 6 24218265
> >
> > [image: View Erik Konijnenburg's profile on LinkedIn]
> > <http://nl.linkedin.com/pub/erik-konijnenburg/47/106/284>
> >
> > Op onze aanbiedingen zijn de Algemene Voorwaarden
> > <http://www.fennek-it.nl/Algemene%20Voorwaarden.pdf> van toepassing.
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/visjs/angular-visjs/pull/26#issuecomment-100005832>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/visjs/angular-visjs/pull/26#issuecomment-100008065>.
>



-- 
Met vriendelijke groet/Kind Regards,

Erik Konijnenburg
http://www.fennek-it.nl
+31 6 24218265

[image: View Erik Konijnenburg's profile on LinkedIn]
<http://nl.linkedin.com/pub/erik-konijnenburg/47/106/284>

Op onze aanbiedingen zijn de Algemene Voorwaarden
<http://www.fennek-it.nl/Algemene%20Voorwaarden.pdf> van toepassing.

**Comment by fennekit** [comment]
I think this problem is caused by the 2 way binding between component and
the parent scope, since I did not supply the 'component' attribute in the
directive in the markup (vis-timeline data="timelineData" options=
"timelineOptions"
events="graphEvents"></vis-timeline>). I think the component should be made
optional in the directive:

scope: {
    data: '=',
    options: '=',
    events: '=',
    component: '=?'
}


On Thu, May 7, 2015 at 10:27 PM, Erik Konijnenburg <
erik.konijnenburg@fennek-it.nl> wrote:

> The error was:
>
> Error: [$compile:nonassign] Expression 'undefined' used with directive
> 'visTimeline' is non-assignable!
>
> http://errors.angularjs.org/1.3.15/$compile/nonassign?p0=undefined&p1=visTimeline
>     at angular.js:63
>     at parentSet (angular.js:7700)
>     at parentValueWatch (angular.js:7713)
>     at Object.regularInterceptedExpression (angular.js:12911)
>     at Scope.$digest (angular.js:14300)
>     at Scope.$apply (angular.js:14571)
>     at done (angular.js:9698)
>     at completeRequest (angular.js:9888)
>     at XMLHttpRequest.requestLoaded (angular.js:9829)
>
> On Thu, May 7, 2015 at 10:26 PM, Chris Jackson <notifications@github.com>
> wrote:
>
>> Hmm - ok, I’ll take a look. This was recently added by someone else and I
>> didn’t test it (I know - that’s bad!). The idea is that you can use it to
>> access the vis object…
>>
>> I’ll take a look in the next day or so…
>>
>> (and thanks for the PR by the way).
>>
>> Cheers
>> Chris
>>
>>
>>
>> > On 7 May 2015, at 21:21, Fennek IT <notifications@github.com> wrote:
>> >
>> > Hi Chris,
>> >
>> > The version from gh-pages did not give any errors while using it. The
>> > master page did. The difference was the $scope.component member
>> >
>> > Erik
>> >
>> > On Thu, May 7, 2015 at 10:12 PM, Chris Jackson <
>> notifications@github.com>
>> > wrote:
>> >
>> > > Thanks.
>> > > Why have you removed the $scope.component member?
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <
>> https://github.com/visjs/angular-visjs/pull/26#issuecomment-100003327>.
>> > >
>> >
>> >
>> >
>> > --
>> > Met vriendelijke groet/Kind Regards,
>> >
>> > Erik Konijnenburg
>> > http://www.fennek-it.nl
>> > +31 6 24218265
>> >
>> > [image: View Erik Konijnenburg's profile on LinkedIn]
>> > <http://nl.linkedin.com/pub/erik-konijnenburg/47/106/284>
>> >
>> > Op onze aanbiedingen zijn de Algemene Voorwaarden
>> > <http://www.fennek-it.nl/Algemene%20Voorwaarden.pdf> van toepassing.
>> > —
>> > Reply to this email directly or view it on GitHub <
>> https://github.com/visjs/angular-visjs/pull/26#issuecomment-100005832>.
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/visjs/angular-visjs/pull/26#issuecomment-100008065>.
>>
>
>
>
> --
> Met vriendelijke groet/Kind Regards,
>
> Erik Konijnenburg
> http://www.fennek-it.nl
> +31 6 24218265
>
> [image: View Erik Konijnenburg's profile on LinkedIn]
> <http://nl.linkedin.com/pub/erik-konijnenburg/47/106/284>
>
> Op onze aanbiedingen zijn de Algemene Voorwaarden
> <http://www.fennek-it.nl/Algemene%20Voorwaarden.pdf> van toepassing.
>



-- 
Met vriendelijke groet/Kind Regards,

Erik Konijnenburg
http://www.fennek-it.nl
+31 6 24218265

[image: View Erik Konijnenburg's profile on LinkedIn]
<http://nl.linkedin.com/pub/erik-konijnenburg/47/106/284>

Op onze aanbiedingen zijn de Algemene Voorwaarden
<http://www.fennek-it.nl/Algemene%20Voorwaarden.pdf> van toepassing.

**Comment by cdjackson** [comment]
You're right... I've just fixed this as per your suggestion and also updated the examples which weren't working (due to a removed framework library).
Can you resubmi this PR now - leaving the component stuff in? Probably just merging master into your repo and resolving the conflicts...

**Comment by fennekit** [comment]
superseeded by #27

**Pull request closed without merging**
